import type { InterventionData } from "./types";
import { emptyCureRecords } from "../../utils/cureRecords";

export const loadSmsPreference = (): boolean => {
  try {
    return window.localStorage.getItem("interventions-pcd:sms-enabled") === "true";
  } catch {
    return false;
  }
};

export const emptyInterventionData: InterventionData = {
  documentId: "",
  interventionId: "",
  network: "",
  infrastructure: "",
  oagID: "",
  na: "",
  cid: "",
  clientName: "",
  interventionDescription: "",
  clientID: "",
  mainAddress: "",
  streetName: "",
  streetNumber: "",
  streetAlpha: "",
  postalCode: "",
  city: "",
  addressDetails: "",
  mailbox: "",
  floor: "",
  apartment: "",
  blockNumber: "",
  clientsOnAddress: "",
  addressClients: [],
  LOMKey: "",
  phone: "",
  wctLink: "",
  displayAllFields: false,
  snowReceived: "",
  snowSent: "",
  snowMentioned: "",
  snowMentionedCreatedAt: null,
  snowReceivedCreatedAt: null,
  snowSentCreatedAt: null,
  isSnowReceivedPending: false,
  isSnowSentPending: false,
  snowStatus: "pending",
  isResPending: false,
  resConsultedDate: null,
  snowReceivedConsultedDate: null,
  snowSentConsultedDate: null,
  resReviewedDate: null,
  snowReceivedReviewedDate: null,
  snowSentReviewedDate: null,
  otherReviewedDate: null,
  cureReviewedDate: null,
  questionReviewedDate: null,
  isUnclear: false,
  addressConfirmation: "none",
  isGoodExample: false,
  isSnow: false,
  comment: "",
  commentSegmentAddressConfirmation: "",
  commentSegmentTechDetailOnAddress: "",
  commentSegmentClientsOnAddress: "",
  commentSegmentGeneralInfo: "",
  commentActionCure: "",
  commentActionResiliation: "",
  commentActionSnowReceived: "",
  commentActionSnowSent: "",
  commentActionBci: "",
  commentActionTache173: "",
  commentActionTache79: "",
  commentActionTache96: "",
  bciNumber: "",
  wioNumber: "",
  tache173Content: "",
  tache79Content: "",
  tache79JobId: "",
  tache96Content: "",
  tache96SnowId: "",
  additionalInformation: "",
  cure: "noCure",
  cureRecords: emptyCureRecords(),
  curePendingSince: null,
  smsEnabled: loadSmsPreference(),
  status: "on hold",
  postponedDate: null,
  createdAt: null,
  updatedAt: null,
  lastRevuAt: null,
};
